// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateLeadTracker.Console.EfCore.Context;

#nullable disable

namespace RealEstateLeadTracker.Console.EfCore.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260227003650_FixSnapshotLeadEntity")]
    partial class FixSnapshotLeadEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstateLeadTracker.Console.EfCore.Entities.Lead", b =>
                {
                    b.Property<int>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadId"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LeadId")
                        .HasName("PK__Leads__73EF78FA9559F614");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("RealEstateLeadTracker.Console.EfCore.Entities.LeadNote", b =>
                {
                    b.Property<int>("LeadNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadNoteId"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LeadNoteId")
                        .HasName("PK__LeadNote__C8B0B7B6F7A87B17");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadNotes", (string)null);
                });

            modelBuilder.Entity("RealEstateLeadTracker.Console.EfCore.Entities.LeadNote", b =>
                {
                    b.HasOne("RealEstateLeadTracker.Console.EfCore.Entities.Lead", "Lead")
                        .WithMany("LeadNotes")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("RealEstateLeadTracker.Console.EfCore.Entities.Lead", b =>
                {
                    b.Navigation("LeadNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
